/**
 * Megaton API
 * JSON API for the Megaton Cloud Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@megaton.cloud
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The BaselineExecution model module.
* @module model/BaselineExecution
* @version 1.0.0
*/
export default class BaselineExecution {
    /**
    * Constructs a new <code>BaselineExecution</code>.
    * @alias module:model/BaselineExecution
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>BaselineExecution</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/BaselineExecution} obj Optional instance to populate.
    * @return {module:model/BaselineExecution} The populated <code>BaselineExecution</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BaselineExecution();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('terminatedReason')) {
                obj['terminatedReason'] = ApiClient.convertToType(data['terminatedReason'], 'String');
            }
            if (data.hasOwnProperty('pointOfPresence')) {
                obj['pointOfPresence'] = ApiClient.convertToType(data['pointOfPresence'], 'String');
            }
            if (data.hasOwnProperty('statusTimestamp')) {
                obj['statusTimestamp'] = ApiClient.convertToType(data['statusTimestamp'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Number} id
    */
    id = undefined;
    /**
    * @member {String} status
    */
    status = undefined;
    /**
    * @member {String} terminatedReason
    */
    terminatedReason = undefined;
    /**
    * @member {String} pointOfPresence
    */
    pointOfPresence = undefined;
    /**
    * @member {String} statusTimestamp
    */
    statusTimestamp = undefined;








}


