/**
 * Megaton API
 * JSON API for the Megaton Cloud Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@megaton.cloud
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import HARLog from './HARLog';





/**
* The HAR model module.
* @module model/HAR
* @version 1.0.0
*/
export default class HAR {
    /**
    * Constructs a new <code>HAR</code>.
    * @alias module:model/HAR
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>HAR</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/HAR} obj Optional instance to populate.
    * @return {module:model/HAR} The populated <code>HAR</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HAR();

            
            
            

            if (data.hasOwnProperty('log')) {
                obj['log'] = HARLog.constructFromObject(data['log']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/HARLog} log
    */
    log = undefined;








}


