/**
 * Megaton API
 * JSON API for the Megaton Cloud Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@megaton.cloud
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import HARRequest from './HARRequest';





/**
* The HARLogEntry model module.
* @module model/HARLogEntry
* @version 1.0.0
*/
export default class HARLogEntry {
    /**
    * Constructs a new <code>HARLogEntry</code>.
    * @alias module:model/HARLogEntry
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>HARLogEntry</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/HARLogEntry} obj Optional instance to populate.
    * @return {module:model/HARLogEntry} The populated <code>HARLogEntry</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HARLogEntry();

            
            
            

            if (data.hasOwnProperty('startedDateTime')) {
                obj['startedDateTime'] = ApiClient.convertToType(data['startedDateTime'], 'String');
            }
            if (data.hasOwnProperty('request')) {
                obj['request'] = HARRequest.constructFromObject(data['request']);
            }
        }
        return obj;
    }

    /**
    * @member {String} startedDateTime
    */
    startedDateTime = undefined;
    /**
    * @member {module:model/HARRequest} request
    */
    request = undefined;








}


