/**
 * Megaton API
 * JSON API for the Megaton Cloud Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@megaton.cloud
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import HARLogEntry from './HARLogEntry';





/**
* The HARLog model module.
* @module model/HARLog
* @version 1.0.0
*/
export default class HARLog {
    /**
    * Constructs a new <code>HARLog</code>.
    * @alias module:model/HARLog
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>HARLog</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/HARLog} obj Optional instance to populate.
    * @return {module:model/HARLog} The populated <code>HARLog</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HARLog();

            
            
            

            if (data.hasOwnProperty('entries')) {
                obj['entries'] = ApiClient.convertToType(data['entries'], [HARLogEntry]);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/HARLogEntry>} entries
    */
    entries = undefined;








}


