/**
 * Megaton API
 * JSON API for the Megaton Cloud Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@megaton.cloud
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The HARPostData model module.
* @module model/HARPostData
* @version 1.0.0
*/
export default class HARPostData {
    /**
    * Constructs a new <code>HARPostData</code>.
    * @alias module:model/HARPostData
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>HARPostData</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/HARPostData} obj Optional instance to populate.
    * @return {module:model/HARPostData} The populated <code>HARPostData</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HARPostData();

            
            
            

            if (data.hasOwnProperty('mimeType')) {
                obj['mimeType'] = ApiClient.convertToType(data['mimeType'], 'String');
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} mimeType
    */
    mimeType = undefined;
    /**
    * @member {String} text
    */
    text = undefined;








}


