/**
 * Megaton API
 * JSON API for the Megaton Cloud Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@megaton.cloud
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import HARPostData from './HARPostData';
import NameValuePair from './NameValuePair';





/**
* The HARRequest model module.
* @module model/HARRequest
* @version 1.0.0
*/
export default class HARRequest {
    /**
    * Constructs a new <code>HARRequest</code>.
    * @alias module:model/HARRequest
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>HARRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/HARRequest} obj Optional instance to populate.
    * @return {module:model/HARRequest} The populated <code>HARRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HARRequest();

            
            
            

            if (data.hasOwnProperty('method')) {
                obj['method'] = ApiClient.convertToType(data['method'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('httpVersion')) {
                obj['httpVersion'] = ApiClient.convertToType(data['httpVersion'], 'String');
            }
            if (data.hasOwnProperty('cookies')) {
                obj['cookies'] = ApiClient.convertToType(data['cookies'], [NameValuePair]);
            }
            if (data.hasOwnProperty('headers')) {
                obj['headers'] = ApiClient.convertToType(data['headers'], [NameValuePair]);
            }
            if (data.hasOwnProperty('postData')) {
                obj['postData'] = HARPostData.constructFromObject(data['postData']);
            }
        }
        return obj;
    }

    /**
    * @member {String} method
    */
    method = undefined;
    /**
    * @member {String} url
    */
    url = undefined;
    /**
    * @member {String} httpVersion
    */
    httpVersion = undefined;
    /**
    * @member {Array.<module:model/NameValuePair>} cookies
    */
    cookies = undefined;
    /**
    * @member {Array.<module:model/NameValuePair>} headers
    */
    headers = undefined;
    /**
    * @member {module:model/HARPostData} postData
    */
    postData = undefined;








}


