/**
 * Megaton API
 * JSON API for the Megaton Cloud Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@megaton.cloud
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The HTTPResponse model module.
* @module model/HTTPResponse
* @version 1.0.0
*/
export default class HTTPResponse {
    /**
    * Constructs a new <code>HTTPResponse</code>.
    * @alias module:model/HTTPResponse
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>HTTPResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/HTTPResponse} obj Optional instance to populate.
    * @return {module:model/HTTPResponse} The populated <code>HTTPResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HTTPResponse();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('scriptEntryId')) {
                obj['scriptEntryId'] = ApiClient.convertToType(data['scriptEntryId'], 'Number');
            }
            if (data.hasOwnProperty('pointOfPresence')) {
                obj['pointOfPresence'] = ApiClient.convertToType(data['pointOfPresence'], 'String');
            }
            if (data.hasOwnProperty('vuId')) {
                obj['vuId'] = ApiClient.convertToType(data['vuId'], 'String');
            }
            if (data.hasOwnProperty('messageSize')) {
                obj['messageSize'] = ApiClient.convertToType(data['messageSize'], 'Number');
            }
            if (data.hasOwnProperty('duration')) {
                obj['duration'] = ApiClient.convertToType(data['duration'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Number');
            }
            if (data.hasOwnProperty('receivedTimestamp')) {
                obj['receivedTimestamp'] = ApiClient.convertToType(data['receivedTimestamp'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Number} id
    */
    id = undefined;
    /**
    * @member {Number} scriptEntryId
    */
    scriptEntryId = undefined;
    /**
    * @member {String} pointOfPresence
    */
    pointOfPresence = undefined;
    /**
    * @member {String} vuId
    */
    vuId = undefined;
    /**
    * @member {Number} messageSize
    */
    messageSize = undefined;
    /**
    * @member {String} duration
    */
    duration = undefined;
    /**
    * @member {Number} status
    */
    status = undefined;
    /**
    * @member {String} receivedTimestamp
    */
    receivedTimestamp = undefined;








}


