/**
 * Megaton API
 * JSON API for the Megaton Cloud Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@megaton.cloud
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The HTTPScriptEntry model module.
* @module model/HTTPScriptEntry
* @version 1.0.0
*/
export default class HTTPScriptEntry {
    /**
    * Constructs a new <code>HTTPScriptEntry</code>.
    * @alias module:model/HTTPScriptEntry
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>HTTPScriptEntry</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/HTTPScriptEntry} obj Optional instance to populate.
    * @return {module:model/HTTPScriptEntry} The populated <code>HTTPScriptEntry</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HTTPScriptEntry();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('orderId')) {
                obj['orderId'] = ApiClient.convertToType(data['orderId'], 'Number');
            }
            if (data.hasOwnProperty('delay')) {
                obj['delay'] = ApiClient.convertToType(data['delay'], 'String');
            }
            if (data.hasOwnProperty('method')) {
                obj['method'] = ApiClient.convertToType(data['method'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Number} id
    */
    id = undefined;
    /**
    * @member {Number} orderId
    */
    orderId = undefined;
    /**
    * @member {String} delay
    */
    delay = undefined;
    /**
    * @member {String} method
    */
    method = undefined;
    /**
    * @member {String} url
    */
    url = undefined;
    /**
    * @member {String} version
    */
    version = undefined;








}


