/**
 * Megaton API
 * JSON API for the Megaton Cloud Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@megaton.cloud
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import UseCase from './UseCase';





/**
* The LoadDistributionEntry model module.
* @module model/LoadDistributionEntry
* @version 1.0.0
*/
export default class LoadDistributionEntry {
    /**
    * Constructs a new <code>LoadDistributionEntry</code>.
    * @alias module:model/LoadDistributionEntry
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>LoadDistributionEntry</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/LoadDistributionEntry} obj Optional instance to populate.
    * @return {module:model/LoadDistributionEntry} The populated <code>LoadDistributionEntry</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LoadDistributionEntry();

            
            
            

            if (data.hasOwnProperty('useCase')) {
                obj['useCase'] = UseCase.constructFromObject(data['useCase']);
            }
            if (data.hasOwnProperty('pointOfPresence')) {
                obj['pointOfPresence'] = ApiClient.convertToType(data['pointOfPresence'], 'String');
            }
            if (data.hasOwnProperty('vuCount')) {
                obj['vuCount'] = ApiClient.convertToType(data['vuCount'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/UseCase} useCase
    */
    useCase = undefined;
    /**
    * @member {String} pointOfPresence
    */
    pointOfPresence = undefined;
    /**
    * @member {Number} vuCount
    */
    vuCount = undefined;








}


