/**
 * Megaton API
 * JSON API for the Megaton Cloud Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@megaton.cloud
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The OAuthToken model module.
* @module model/OAuthToken
* @version 1.0.0
*/
export default class OAuthToken {
    /**
    * Constructs a new <code>OAuthToken</code>.
    * @alias module:model/OAuthToken
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>OAuthToken</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/OAuthToken} obj Optional instance to populate.
    * @return {module:model/OAuthToken} The populated <code>OAuthToken</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OAuthToken();

            
            
            

            if (data.hasOwnProperty('access_token')) {
                obj['access_token'] = ApiClient.convertToType(data['access_token'], 'String');
            }
            if (data.hasOwnProperty('expires_in')) {
                obj['expires_in'] = ApiClient.convertToType(data['expires_in'], 'Number');
            }
            if (data.hasOwnProperty('scope')) {
                obj['scope'] = ApiClient.convertToType(data['scope'], 'String');
            }
            if (data.hasOwnProperty('tenant_id')) {
                obj['tenant_id'] = ApiClient.convertToType(data['tenant_id'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {String} access_token
    */
    access_token = undefined;
    /**
    * @member {Number} expires_in
    */
    expires_in = undefined;
    /**
    * @member {String} scope
    */
    scope = undefined;
    /**
    * @member {Number} tenant_id
    */
    tenant_id = undefined;








}


