/**
 * Megaton API
 * JSON API for the Megaton Cloud Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@megaton.cloud
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Tenant model module.
* @module model/Tenant
* @version 1.0.0
*/
export default class Tenant {
    /**
    * Constructs a new <code>Tenant</code>.
    * @alias module:model/Tenant
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Tenant</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Tenant} obj Optional instance to populate.
    * @return {module:model/Tenant} The populated <code>Tenant</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Tenant();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('loadAuthToken')) {
                obj['loadAuthToken'] = ApiClient.convertToType(data['loadAuthToken'], 'String');
            }
            if (data.hasOwnProperty('nickname')) {
                obj['nickname'] = ApiClient.convertToType(data['nickname'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Number} id
    */
    id = undefined;
    /**
    * @member {String} loadAuthToken
    */
    loadAuthToken = undefined;
    /**
    * @member {String} nickname
    */
    nickname = undefined;
    /**
    * @member {String} email
    */
    email = undefined;








}


