/**
 * Megaton API
 * JSON API for the Megaton Cloud Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@megaton.cloud
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The TestPlanPatchOperation model module.
* @module model/TestPlanPatchOperation
* @version 1.0.0
*/
export default class TestPlanPatchOperation {
    /**
    * Constructs a new <code>TestPlanPatchOperation</code>.
    * @alias module:model/TestPlanPatchOperation
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>TestPlanPatchOperation</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TestPlanPatchOperation} obj Optional instance to populate.
    * @return {module:model/TestPlanPatchOperation} The populated <code>TestPlanPatchOperation</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TestPlanPatchOperation();

            
            
            

            if (data.hasOwnProperty('op')) {
                obj['op'] = ApiClient.convertToType(data['op'], 'String');
            }
            if (data.hasOwnProperty('path')) {
                obj['path'] = ApiClient.convertToType(data['path'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} op
    */
    op = undefined;
    /**
    * @member {String} path
    */
    path = undefined;
    /**
    * @member {String} value
    */
    value = undefined;








}


