/**
 * Megaton API
 * JSON API for the Megaton Cloud Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@megaton.cloud
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The UseCase model module.
* @module model/UseCase
* @version 1.0.0
*/
export default class UseCase {
    /**
    * Constructs a new <code>UseCase</code>.
    * @alias module:model/UseCase
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>UseCase</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UseCase} obj Optional instance to populate.
    * @return {module:model/UseCase} The populated <code>UseCase</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UseCase();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Number} id
    */
    id = undefined;
    /**
    * @member {String} name
    */
    name = undefined;








}


