/**
 * Megaton API
 * JSON API for the Megaton Cloud Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@megaton.cloud
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import BaselineExecution from '../model/BaselineExecution';
import BaselineExecutionSpec from '../model/BaselineExecutionSpec';

/**
* BaselineExecutions service.
* @module api/BaselineExecutionsApi
* @version 1.0.0
*/
export default class BaselineExecutionsApi {

    /**
    * Constructs a new BaselineExecutionsApi. 
    * @alias module:api/BaselineExecutionsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Execute baseline
     * Executes a baseline for a specified use-case
     * @param {Number} useCaseId 
     * @param {module:model/BaselineExecutionSpec} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/BaselineExecution} and HTTP response
     */
    executeBaselineWithHttpInfo(useCaseId, body) {
      let postBody = body;

      // verify the required parameter 'useCaseId' is set
      if (useCaseId === undefined || useCaseId === null) {
        throw new Error("Missing the required parameter 'useCaseId' when calling executeBaseline");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling executeBaseline");
      }


      let pathParams = {
        'useCaseId': useCaseId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['password'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = BaselineExecution;

      return this.apiClient.callApi(
        '/v1/tenants/me/use-cases/{useCaseId}/baseline-executions', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Execute baseline
     * Executes a baseline for a specified use-case
     * @param {Number} useCaseId 
     * @param {module:model/BaselineExecutionSpec} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/BaselineExecution}
     */
    executeBaseline(useCaseId, body) {
      return this.executeBaselineWithHttpInfo(useCaseId, body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get baseline executions
     * Retrieve all executed baselines for a specified use-case
     * @param {Number} useCaseId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/BaselineExecution>} and HTTP response
     */
    getBaselineExecutionsWithHttpInfo(useCaseId) {
      let postBody = null;

      // verify the required parameter 'useCaseId' is set
      if (useCaseId === undefined || useCaseId === null) {
        throw new Error("Missing the required parameter 'useCaseId' when calling getBaselineExecutions");
      }


      let pathParams = {
        'useCaseId': useCaseId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['password'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [BaselineExecution];

      return this.apiClient.callApi(
        '/v1/tenants/me/use-cases/{useCaseId}/baseline-executions', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get baseline executions
     * Retrieve all executed baselines for a specified use-case
     * @param {Number} useCaseId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/BaselineExecution>}
     */
    getBaselineExecutions(useCaseId) {
      return this.getBaselineExecutionsWithHttpInfo(useCaseId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
