/**
 * Megaton API
 * JSON API for the Megaton Cloud Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@megaton.cloud
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import HAR from '../model/HAR';
import HTTPScriptEntry from '../model/HTTPScriptEntry';

/**
* HARImports service.
* @module api/HARImportsApi
* @version 1.0.0
*/
export default class HARImportsApi {

    /**
    * Constructs a new HARImportsApi. 
    * @alias module:api/HARImportsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Import HAR
     * Sets the HTTP script for a use-case using an HTTP Archive
     * @param {Number} useCaseId 
     * @param {module:model/HAR} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/HTTPScriptEntry>} and HTTP response
     */
    importHarWithHttpInfo(useCaseId, body) {
      let postBody = body;

      // verify the required parameter 'useCaseId' is set
      if (useCaseId === undefined || useCaseId === null) {
        throw new Error("Missing the required parameter 'useCaseId' when calling importHar");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling importHar");
      }


      let pathParams = {
        'useCaseId': useCaseId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['password'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = [HTTPScriptEntry];

      return this.apiClient.callApi(
        '/v1/tenants/me/use-cases/{useCaseId}/har-imports', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Import HAR
     * Sets the HTTP script for a use-case using an HTTP Archive
     * @param {Number} useCaseId 
     * @param {module:model/HAR} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/HTTPScriptEntry>}
     */
    importHar(useCaseId, body) {
      return this.importHarWithHttpInfo(useCaseId, body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
