/**
 * Megaton API
 * JSON API for the Megaton Cloud Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@megaton.cloud
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import TestExecution from '../model/TestExecution';

/**
* TestExecutions service.
* @module api/TestExecutionsApi
* @version 1.0.0
*/
export default class TestExecutionsApi {

    /**
    * Constructs a new TestExecutionsApi. 
    * @alias module:api/TestExecutionsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Execute test plan
     * Executes a specified test plan
     * @param {Number} testPlanId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/TestExecution} and HTTP response
     */
    executeTestWithHttpInfo(testPlanId) {
      let postBody = null;

      // verify the required parameter 'testPlanId' is set
      if (testPlanId === undefined || testPlanId === null) {
        throw new Error("Missing the required parameter 'testPlanId' when calling executeTest");
      }


      let pathParams = {
        'testPlanId': testPlanId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['password'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TestExecution;

      return this.apiClient.callApi(
        '/v1/tenants/me/test-plans/{testPlanId}/test-executions', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Execute test plan
     * Executes a specified test plan
     * @param {Number} testPlanId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/TestExecution}
     */
    executeTest(testPlanId) {
      return this.executeTestWithHttpInfo(testPlanId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get test executions
     * Retrieve all executed tests for a specified test plan
     * @param {Number} testPlanId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/TestExecution>} and HTTP response
     */
    getTestExecutionsWithHttpInfo(testPlanId) {
      let postBody = null;

      // verify the required parameter 'testPlanId' is set
      if (testPlanId === undefined || testPlanId === null) {
        throw new Error("Missing the required parameter 'testPlanId' when calling getTestExecutions");
      }


      let pathParams = {
        'testPlanId': testPlanId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['password'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [TestExecution];

      return this.apiClient.callApi(
        '/v1/tenants/me/test-plans/{testPlanId}/test-executions', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get test executions
     * Retrieve all executed tests for a specified test plan
     * @param {Number} testPlanId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/TestExecution>}
     */
    getTestExecutions(testPlanId) {
      return this.getTestExecutionsWithHttpInfo(testPlanId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
