/**
 * Megaton API
 * JSON API for the Megaton Cloud Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@megaton.cloud
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import HTTPResponse from '../model/HTTPResponse';

/**
* TestHTTPResponses service.
* @module api/TestHTTPResponsesApi
* @version 1.0.0
*/
export default class TestHTTPResponsesApi {

    /**
    * Constructs a new TestHTTPResponsesApi. 
    * @alias module:api/TestHTTPResponsesApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Get test responses
     * Retrieve HTTP responses for a specified test exeuction
     * @param {Number} testPlanId 
     * @param {Number} executionId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/HTTPResponse>} and HTTP response
     */
    getTestHttpResponsesWithHttpInfo(testPlanId, executionId) {
      let postBody = null;

      // verify the required parameter 'testPlanId' is set
      if (testPlanId === undefined || testPlanId === null) {
        throw new Error("Missing the required parameter 'testPlanId' when calling getTestHttpResponses");
      }

      // verify the required parameter 'executionId' is set
      if (executionId === undefined || executionId === null) {
        throw new Error("Missing the required parameter 'executionId' when calling getTestHttpResponses");
      }


      let pathParams = {
        'testPlanId': testPlanId,
        'executionId': executionId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['password'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [HTTPResponse];

      return this.apiClient.callApi(
        '/v1/tenants/me/test-plans/{testPlanId}/test-executions/{executionId}/http-responses', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get test responses
     * Retrieve HTTP responses for a specified test exeuction
     * @param {Number} testPlanId 
     * @param {Number} executionId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/HTTPResponse>}
     */
    getTestHttpResponses(testPlanId, executionId) {
      return this.getTestHttpResponsesWithHttpInfo(testPlanId, executionId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
